// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammingTask.Data;

#nullable disable

namespace ProgrammingTask.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221211015235_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProgrammingTask.Models.CalculationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CalculationLogId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculationLogId");

                    b.ToTable("CalculationItem");
                });

            modelBuilder.Entity("ProgrammingTask.Models.CalculationLog", b =>
                {
                    b.Property<int>("CalculationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalculationLogId"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("CalculationLogId");

                    b.ToTable("CalculationLogs");
                });

            modelBuilder.Entity("ProgrammingTask.Models.CalculationItem", b =>
                {
                    b.HasOne("ProgrammingTask.Models.CalculationLog", "CalculationLog")
                        .WithMany("CalculationItems")
                        .HasForeignKey("CalculationLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationLog");
                });

            modelBuilder.Entity("ProgrammingTask.Models.CalculationLog", b =>
                {
                    b.Navigation("CalculationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
